from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO

def create_quiz_pdf(quiz_data):
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    #title
    #------------------------------
    story.append(Paragraph("Quiz Generated by Assessly", styles['Title']))
    story.append(Spacer(1, 12))

    #questions
    # -----------------------------
    for i, q in enumerate(quiz_data):
        question_text = q.get('question', '')
        options = q.get('options', [])
        
        story.append(Paragraph(f"Q{i+1}: {question_text}", styles['Normal']))
        story.append(Spacer(1, 6))
        
        option_labels = ['a)', 'b)', 'c)', 'd)']
        for idx, opt in enumerate(options):
            label = option_labels[idx] if idx < len(option_labels) else '-'
            story.append(Paragraph(f"{label} {opt}", styles['Normal']))
        
        story.append(Spacer(1, 12))

    # answer key at last page
    #--------------------------------------
    story.append(PageBreak())
    story.append(Paragraph("Answer Key", styles['Title']))
    story.append(Spacer(1, 12))

    option_labels = ['a)', 'b)', 'c)', 'd)']

    for i, q in enumerate(quiz_data):
        correct_answer = q.get('correct_answer', 'N/A')
        options = q.get('options', [])
        correct_label = ""
        
        for idx, opt in enumerate(options):
            if str(opt).strip() == str(correct_answer).strip():
                if idx < len(option_labels):
                    correct_label = option_labels[idx]
                break
        
        story.append(Paragraph(f"Q{i+1}: {correct_label} {correct_answer}", styles['Normal']))
        story.append(Spacer(1, 6))

    doc.build(story)
    buffer.seek(0)
    return buffer
